bot:
  token: 1472060655:AAHJhYV74wmWwxisHEmWAtNfi83OAW7WJ-c
  name: capitalistBot
  admin: 1385360520
  url: https://t.me/WorkCapitalist_bot
  chat: myChat
  urlStat: tgstat
  urlPayments: payments
  adminUsername: admin

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/capitalist_bot
    username: postgres
    password: 91823God